### ISSUE TITLE
Newly launched servers need to already be connected to the fediverse

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/www-mastodon#83] opened 2022-12-06 11:18 UTC

**Comment by samtaggart** [comment] 2022-12-07 13:58
Reached out to Drew about this one.

**Comment by samtaggart** [comment] 2022-12-07 14:02
I didn't find anything in Mastodon's documentation (https://docs.joinmastodon.org/). Drew pointed me to this link: https://github.com/brodi1/activitypub-relays (cc: @xmonader)

**Comment by Mahmoud-Emad** [comment] 2022-12-14 14:12
WIP: The image updated in https://github.com/threefoldtech/tf-images/pull/120 and under testing

**Comment by Mahmoud-Emad** [comment] 2022-12-14 15:47
WIP:
Newly launched servers connected to the fediverse
![image](https://user-images.githubusercontent.com/57001890/207642186-9268c60a-3215-454f-87ad-9bac43295891.png)

**Comment by Mahmoud-Emad** [comment] 2022-12-15 08:53
Should be fixed in https://github.com/threefoldtech/www-mastodon/pull/130
### Steps to verify.
- Deploy a new instance.
- Login with admin credentials. 
- Go to preference -> administration -> relays.
- Look at relays should be like.

![image](https://user-images.githubusercontent.com/57001890/207815267-01beeaf0-3ca9-4b6d-989a-2820beff9871.png)


- Click on the Federated tab on the home page.

![image](https://user-images.githubusercontent.com/57001890/207816769-5a17967a-74c0-409a-a2b2-17be05ec16b5.png)


 - New servers should see posts come from other servers now.
 
![image](https://user-images.githubusercontent.com/57001890/207816586-390c4672-05c9-4b15-a85f-556b0cd5eb69.png)

**Comment by Mahmoud-Emad** [comment] 2022-12-15 13:17
PS: I got an issue when posting a new tweet in the mastodon instance, I'm going to debug and fix it.

**Comment by Mahmoud-Emad** [comment] 2022-12-15 15:55
The issue mentioned above should be fixed in https://github.com/threefoldtech/www-mastodon/pull/135, but still there is another issue I think it's not about our image, the issue is when you want to add a new relay and this relay is broken if you going to make an action like posting a new tweet or any post request I guess you'll face `bad gateway`, I think this error is coming from the mastodon code not issue in our provider.

and to solve this issue you have to log into the machine then
```sh
cd ..
cd docker
docker-compose down 
docker-compose up
```

**Comment by mohamedamer453** [comment] 2022-12-22 11:21
Verified on https://getmastodon.threefold.io/

After navigating to `preference -> administration -> relays` i was able to find the added relays it's not the same amount of relays mentioned above, but after checking #135 i found that these are indeed the ones left after removing the broken ones.

![image](https://user-images.githubusercontent.com/101194226/209123046-0b75895b-eb46-44c5-bac5-2acc1a32f84a.png)

and after navigating to the `Federated` tab i was able to see posts coming from other servers.

![image](https://user-images.githubusercontent.com/101194226/209123237-4e6cfad9-05c0-45ed-bdb8-806bf85d5287.png)

**Closed as completed by mohamedamer453** 2022-12-22 11:21 UTC
Labels: type_feature
